services:
  postgres:
    image: postgres:16-alpine
    container_name: zenithly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zenithly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zenithly"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: zenithly-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    container_name: zenithly-docs
    restart: unless-stopped
    ports:
      - "5050:5050"

volumes:
  postgres_data:
    driver: local
