version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: zenithly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zenithly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zenithly"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  api:
    build: .
    container_name: zenithly-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/zenithly
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: ["yarn", "start"]

  docs:
    build:
      context: ./docs
    container_name: zenithly-docs
    restart: unless-stopped
    ports:
      - "5050:5050"
    command: ["yarn", "docs:start"]

volumes:
  postgres_data:
    driver: local
