name: CI/CD Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: zenithly_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Create test environment file
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/zenithly_test" > .env
          echo "JWT_SECRET=test_secret_key_for_testing_only" >> .env
          echo "BETTER_AUTH_SECRET=test_better_auth_secret_for_testing" >> .env
          echo "PORT=8080" >> .env
          echo "NODE_ENV=test" >> .env

      - name: Run database migrations
        run: yarn db:migrate

      - name: Run linting
        run: yarn lint

      - name: Run tests
        run: yarn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build Docs
        run: npx vitepress build docs

      - name: Build application
        run: yarn build || echo "No build script found, skipping build step"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export PATH="$HOME/.yarn/bin:$PATH"

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd /home/ubuntu/zenithly-server || cd /var/www/zenithly-server || exit 1

            git pull origin master

            set -a
            . .env
            set +a

            yarn install

            yarn db:migrate

            pm2 start ecosystem.config.cjs --env production --update-env

            pm2 status
